# Generated by Django 3.0.6 on 2020-06-02 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nostaldja', '0003_auto_20200530_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='fad',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
